# Generated by Django 3.1.6 on 2021-02-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Анонс')),
                ('full_text', models.TextField(verbose_name='Статья')),
                ('created_at', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
